# .rubocop.yml for Rails project

plugins:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.4.4   # your Ruby version
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'db/schema.rb'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: true

Metrics/MethodLength:
  Max: 30
Metrics/BlockLength:
  Max: 35
